### ISSUE TITLE
ImportError: No module named 'resnet_v1_101_rcnn_selsa'

### ISSUE THREAD

**Issue by ron5569** [happywu/Sequence-Level-Semantics-Aggregation#5]
Hey I ran the follwing command using  Python 3.5.2 Ubuntu 16.04 

python experiments/selsa/test.py --cfg experiments/selsa/cfgs/resnet_v1_101_rcnn_selsa_aug.yaml --test-pretrained ./model/pretrained_model/selsa_rcnn_vid

And I got the following error 

Traceback (most recent call last):
  File "/home/indoordesk/project/Sequence-Level-Semantics-Aggregation/experiments/selsa/test.py", line 16, in <module>
    import test
  File "/home/indoordesk/project/Sequence-Level-Semantics-Aggregation/experiments/selsa/../../rcnn_selsa/test.py", line 48, in <module>
    from function.test_rcnn import test_rcnn
  File "/home/indoordesk/project/Sequence-Level-Semantics-Aggregation/experiments/selsa/../../rcnn_selsa/function/test_rcnn.py", line 19, in <module>
    from symbols import *
  File "/home/indoordesk/project/Sequence-Level-Semantics-Aggregation/experiments/selsa/../../rcnn_selsa/symbols/__init__.py", line 1, in <module>
    import resnet_v1_101_rcnn_selsa
ImportError: No module named 'resnet_v1_101_rcnn_selsa'

**Comment by ron5569** [comment]
OK just  note that this repo is based on Python 2!
